### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by chenfangzhi123** [yiyingcanfeng/hexo-blog-admin#1]
可以有一些示例数据，像管理员账号密码，文章示例，不然下载了还得跟代码看加密方式自己去跟踪。

**Comment by yiyingcanfeng** [comment]
> 可以有一些示例数据，像管理员账号密码，文章示例，不然下载了还得跟代码看加密方式自己去跟踪。
后台管理的demo能正常访问了，默认的用户名和密码是admin 111111，后台服务挂掉了刚刚才注意到

**Comment by chenfangzhi123** [comment]
我的意思是我们下载了代码看代码时候的sql，仅有表结构，示例数据没有

**Comment by yiyingcanfeng** [comment]
> 我的意思是我们下载了代码看代码时候的sql，仅有表结构，示例数据没有

已更新sql脚本
